#!/run/current-system/sw/bin/bash

response=$(curl https://am.i.mullvad.net/json)
connected=$(echo $response | jq -r '.mullvad_exit_ip')
hostname=$(echo $response | jq -r '.mullvad_exit_ip_hostname')
$connected &&
    status=$(echo $hostname | awk -F '-' '{print $1, $2}' OFS='-') ||
    status="OFF!"
echo " VPN: $status"
